steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/houzz-to-zoho', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/houzz-to-zoho']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'houzz-to-zoho'
      - '--image'
      - 'gcr.io/$PROJECT_ID/houzz-to-zoho'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Set environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'houzz-to-zoho'
      - '--region'
      - 'us-central1'
      - '--update-env-vars-file'
      - 'env.yaml'

images:
  - 'gcr.io/$PROJECT_ID/houzz-to-zoho'
